MATCH (n) DETACH DELETE n;
CREATE (n:Base:Domain {name: 'TEST.LOCAL', domain: 'TEST.LOCAL'});
CREATE (n:Base:User {name: 'JMARIA@TEST.LOCAL', domain: 'TEST.LOCAL', displayname: 'Juan María', title: 'CEO', department: 'Dirección', enabled: true});
CREATE (n:Base:User {name: 'PGONZAL@TEST.LOCAL', domain: 'TEST.LOCAL', displayname: 'Paula González', title: 'Manager IT', department: 'IT', admincount: true, enabled: true});
CREATE (n:Base:User {name: 'LORTIZ@TEST.LOCAL', domain: 'TEST.LOCAL', displayname: 'Luis Ortiz', title: 'Developer', department: 'IT', dontreqpreauth: true, enabled: true});
CREATE (n:Base:User {name: 'CFDEZ@TEST.LOCAL', domain: 'TEST.LOCAL', displayname: 'Carla Fernández', title: 'Developer', department: 'IT', enabled: true});
CREATE (n:Base:User {name: 'MSANZ@TEST.LOCAL', domain: 'TEST.LOCAL', displayname: 'Marta Sanz', title: 'Account Exec', department: 'Ventas', enabled: true});
CREATE (n:Base:User {name: 'SVC_BACKUP@TEST.LOCAL', domain: 'TEST.LOCAL', displayname: 'svc-backup', serviceprincipalnames: ['CIFS/WKS-FP-01.test.local', 'CIFS/SRV-ARCHIVE.test.local'], admincount: true, enabled: true});
CREATE (n:Base:User {name: 'SVC_HELPDESK@TEST.LOCAL', domain: 'TEST.LOCAL', displayname: 'svc-helpdesk', enabled: true});
CREATE (n:Base:Group {name: 'DOMAIN ADMINS@TEST.LOCAL', domain: 'TEST.LOCAL', admincount: true});
CREATE (n:Base:Group {name: 'IT-ADMINS@TEST.LOCAL', domain: 'TEST.LOCAL', admincount: true});
CREATE (n:Base:Group {name: 'HELPDESK@TEST.LOCAL', domain: 'TEST.LOCAL'});
CREATE (n:Base:Group {name: 'ALL-STAFF@TEST.LOCAL', domain: 'TEST.LOCAL'});
CREATE (n:Base:Computer {name: 'DC01.TEST.LOCAL', domain: 'TEST.LOCAL', operatingsystem: 'Windows Server 2022'});
CREATE (n:Base:Computer {name: 'WKS-FP-01.TEST.LOCAL', domain: 'TEST.LOCAL', operatingsystem: 'Windows 11 Pro'});
CREATE (n:Base:Computer {name: 'WKS-FP-02.TEST.LOCAL', domain: 'TEST.LOCAL', operatingsystem: 'Windows 11 Pro'});
CREATE (n:Base:Computer {name: 'SRV-ARCHIVE.TEST.LOCAL', domain: 'TEST.LOCAL', operatingsystem: 'Windows Server 2019'});
MATCH (a {name: 'PGONZAL@TEST.LOCAL'}), (b {name: 'IT-ADMINS@TEST.LOCAL'}) CREATE (a)-[:MemberOf]->(b);
MATCH (a {name: 'SVC_HELPDESK@TEST.LOCAL'}), (b {name: 'HELPDESK@TEST.LOCAL'}) CREATE (a)-[:MemberOf]->(b);
MATCH (a {name: 'SVC_HELPDESK@TEST.LOCAL'}), (b {name: 'IT-ADMINS@TEST.LOCAL'}) CREATE (a)-[:MemberOf]->(b);
MATCH (a {name: 'SVC_BACKUP@TEST.LOCAL'}), (b {name: 'DOMAIN ADMINS@TEST.LOCAL'}) CREATE (a)-[:MemberOf]->(b);
MATCH (a {name: 'JMARIA@TEST.LOCAL'}), (b {name: 'ALL-STAFF@TEST.LOCAL'}) CREATE (a)-[:MemberOf]->(b);
MATCH (a {name: 'LORTIZ@TEST.LOCAL'}), (b {name: 'ALL-STAFF@TEST.LOCAL'}) CREATE (a)-[:MemberOf]->(b);
MATCH (a {name: 'CFDEZ@TEST.LOCAL'}), (b {name: 'ALL-STAFF@TEST.LOCAL'}) CREATE (a)-[:MemberOf]->(b);
MATCH (a {name: 'MSANZ@TEST.LOCAL'}), (b {name: 'ALL-STAFF@TEST.LOCAL'}) CREATE (a)-[:MemberOf]->(b);
MATCH (a {name: 'CFDEZ@TEST.LOCAL'}), (b {name: 'HELPDESK@TEST.LOCAL'}) CREATE (a)-[:AddMember]->(b);
MATCH (a {name: 'HELPDESK@TEST.LOCAL'}), (b {name: 'SVC_HELPDESK@TEST.LOCAL'}) CREATE (a)-[:GenericAll]->(b);
MATCH (a {name: 'PGONZAL@TEST.LOCAL'}), (b {name: 'JMARIA@TEST.LOCAL'}) CREATE (a)-[:AllExtendedRights]->(b);
MATCH (a {name: 'IT-ADMINS@TEST.LOCAL'}), (b {name: 'WKS-FP-01.TEST.LOCAL'}) CREATE (a)-[:AdminTo]->(b);
MATCH (a {name: 'IT-ADMINS@TEST.LOCAL'}), (b {name: 'WKS-FP-02.TEST.LOCAL'}) CREATE (a)-[:AdminTo]->(b);
MATCH (a {name: 'SVC_BACKUP@TEST.LOCAL'}), (b {name: 'SRV-ARCHIVE.TEST.LOCAL'}) CREATE (a)-[:AdminTo]->(b);
MATCH (a {name: 'WKS-FP-01.TEST.LOCAL'}), (b {name: 'SVC_BACKUP@TEST.LOCAL'}) CREATE (a)-[:HasSession]->(b);
MATCH (a {name: 'WKS-FP-02.TEST.LOCAL'}), (b {name: 'JMARIA@TEST.LOCAL'}) CREATE (a)-[:HasSession]->(b);
MATCH (a {name: 'SVC_BACKUP@TEST.LOCAL'}), (b {name: 'TEST.LOCAL'}) CREATE (a)-[:GetChangesAll]->(b);
MATCH (a {name: 'DC01.TEST.LOCAL'}), (b {name: 'TEST.LOCAL'}) CREATE (a)-[:DCFor]->(b);
MATCH (a {name: 'DOMAIN ADMINS@TEST.LOCAL'}), (b {name: 'DC01.TEST.LOCAL'}) CREATE (a)-[:AllExtendedRights]->(b);
CREATE INDEX usuario_nombre IF NOT EXISTS FOR (u:User) ON (u.name);
CREATE INDEX grupo_nombre IF NOT EXISTS FOR (g:Group) ON (g.name);
CREATE INDEX equipo_nombre IF NOT EXISTS FOR (c:Computer) ON (c.name);
